# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 12:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(max_length=40, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='myuser',
            name='prefered_radius',
            field=models.IntegerField(default=5, help_text='in kilometers'),
        ),
    ]
