# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0004_auto_20160527_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default='profilepictures/default.png', null=True, upload_to='profilepictures/'),
        ),
    ]
