# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0005_auto_20160529_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='prefered_radius',
            field=models.IntegerField(default=100, help_text='in kilometers'),
        ),
    ]
