# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0006_auto_20160601_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profilepictures/default.png', null=True, upload_to='profilepictures/'),
        ),
    ]
