# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, to='api.Food'),
        ),
    ]
