# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160523_1325'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
