# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160524_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='distance',
        ),
    ]
