# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160528_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantsinevent',
            old_name='user_joined',
            new_name='user',
        ),
    ]
