# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
