# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 10, 11, 18, 53, 240000, tzinfo=utc)),
        ),
    ]
