# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160510_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=models.DateTimeField(default='django.utils.timezone.now')),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participantsinevent',
            name='extra_friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='food',
            field=models.ManyToManyField(to='api.Food'),
        ),
    ]
