# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160510_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
    ]
