# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160510_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 10, 15, 39, 1, 533000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 10, 15, 39, 8, 100000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantsinevent',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 10, 15, 39, 21, 844000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
