# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160510_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='participantsinevent',
            name='date_joined',
            field=models.DateTimeField(editable=False),
        ),
    ]
